config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :courses, only: %i[index show]
  resources :students, only: :create
end

app/models/course.rb
# frozen_string_literal: true

class Course < ActiveRecord::Base
  has_and_belongs_to_many :groups

  validates :title, presence: true, uniqueness: true
end

app/models/courses_group.rb
# frozen_string_literal: true

class CoursesGroup < ActiveRecord::Base
end

app/models/group.rb
# frozen_string_literal: true

class Group < ActiveRecord::Base
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :students

  validates :start_dt, presence: true
end

app/models/groups_student.rb
# frozen_string_literal: true

class GroupsStudent < ActiveRecord::Base
end

app/models/student.rb
# frozen_string_literal: true

class Student < ActiveRecord::Base
  has_and_belongs_to_many :groups

  validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ActionController::Base
  before_action :find_course, only: :show

  def index
    @courses = Course.includes(groups: :students).distinct.order('min(groups.start_dt)')
                     .group('courses.id')
                     .pluck('courses.id, courses.title, min(groups.start_dt), count(distinct students.id)')
  end

  def show; end

  private

  def find_course
    @course = Course.includes(:groups).find(params[:id])
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ActionController::Base
  def create
    @student = Student.new(email: student_params[:email])
    @student.group_ids = @student.group_ids << student_params[:group_id]

    if @student.save
      flash[:notice] = 'Successful join the group'
    else
      flash[:alert] = 'Could not join the group'
    end

    redirect_to courses_path
  end

  private

  def student_params
    params.permit(:email, :group_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/courses/index.html.slim
= render 'shared/flashes'
table
  thead
    tr
      th Имя
      th Дата начала
      th Кол-во студентов
  tbody
  - @courses.each do |course|
    tr
      td = link_to course[1], course_path(course[0])
      td = course[2]
      td = course[3]

app/views/courses/show.html.slim
h1 = @course.title
- if @course.groups.any?
  h2 Группы курса
  - @course.groups.each do |group|
    p = group.title
    p = group.start_dt
    - if group.students.any?
      h5 Список студентов
      - group.students.uniq.each do |student|
        p = student.name

    = link_to 'Присоединиться к группе', '#', onclick: "showDiv()"
    #join_div style="display:none;"
      p Введите email
      = form_with(url: students_path, method: :post) do |f|
        = hidden_field_tag 'group_id', group.id
        = text_field_tag 'email'
        = submit_tag 'Отправить'
  br
  br

javascript:
  function showDiv() {
    document.getElementById('join_div').style.display = "block";
  }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_flashes.html.slim
- flash.each do |key, message|
  p class="#{key}" = message